apiVersion: v1
kind: ConfigMap
metadata:
  name: jtl-reporter-config
  labels:
    app: jtl-reporter
data:
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;
      location / {
        proxy_pass http://jtl-reporter-be:5000;
      }
    }
