apiVersion: v1
kind: Secret
metadata:
  name: jtl-reporter-secrets
type: Opaque
data:
  JWT_TOKEN: {{ .Values.secrets.JWT_TOKEN | b64enc }}
  JWT_TOKEN_LOGIN: {{ .Values.secrets.JWT_TOKEN_LOGIN | b64enc }}
