apiVersion: v1
kind: Service
metadata:
  name: samba-service
  labels:
    app: samba
spec:
  ports:
    - name: netbios-ns
      protocol: UDP
      port: 137
      targetPort: 137
    - name: netbios-dgm
      protocol: UDP
      port: 138
      targetPort: 138
    - name: netbios-ssn
      protocol: TCP
      port: 139
      targetPort: 139
    - name: microsoft-ds
      protocol: TCP
      port: 445
      targetPort: 445
  selector:
    app: samba
  type: ClusterIP  # Cambia a NodePort o LoadBalancer si necesitas exponerlo externamente
