apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
spec:
  selector:
    app: nginx-proxy
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  - name: admin
    port: 81
    targetPort: 81
  type: ClusterIP  # Cambiar a LoadBalancer o NodePort si es necesario
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  type: ClusterIP
