replicaCount: 1
image:
  backend: novyl/jtl-reporter-be:v5.0.2
  frontend: novyl/jtl-reporter-fe:v5.0.2
  db: timescale/timescaledb-ha:latest

db:
  postgresHostAuthMethod: trust
  storage: 10Gi

env:
  backend:
    JWT_TOKEN: ""
    JWT_TOKEN_LOGIN: ""
    DB_HOST: jtl-reporter-db
  frontend:
    BACKEND_HOST: jtl-reporter-be
    BACKEND_PORT: "5000"

service:
  frontend:
    type: ClusterIP
    port: 2020
  backend:
    type: ClusterIP
    port: 5000
  db:
    port: 5432

ingress:
  enabled: false

nginx:
  upstream:
    host: "jtl-reporter-be"
    port: 5000
