apiVersion: v1
kind: Service
metadata:
  name: emby
  #namespace: dev  # Asegúrate de que el namespace es el correcto
spec:
  ports:
  - port: 8096  # El puerto que expondrá el servicio
    targetPort: 8096  # El puerto en el contenedor al que se redirigirá el tráfico
  selector:
    app: emby  # Debe coincidir con las etiquetas del Deployment
  type: ClusterIP  # Puedes cambiar esto a NodePort o LoadBalancer según lo que necesites
