apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  #namespace: dev  # Asegúrate de que el namespace es el correcto
spec:
  ports:
  - port: 9000  # El puerto que expondrá el servicio
    targetPort: 9000  # El puerto en el contenedor al que se redirigirá el tráfico
  selector:
    app: sonarqube  # Debe coincidir con las etiquetas del Deployment
  type: ClusterIP  # Puedes cambiar esto a NodePort o LoadBalancer según lo que necesites
