apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jtl-reporter.fullname" . }}-config
data:
  DATABASE_URL: {{ .Values.env.migration.DATABASE_URL }}
  OPT_OUT_ANALYTICS: {{ .Values.env.migration.OPT_OUT_ANALYTICS | quote }}

  nginx.conf: |
    # Bloque http donde deben definirse las directivas upstream y server
    http {
        # Define el bloque upstream fuera de cualquier bloque server
        upstream backend {
            server {{ .Values.nginx.upstream.host }}:{{ .Values.nginx.upstream.port }};
        }

        # Configuración del servidor NGINX
        server {
            listen 80;

            location / {
                proxy_pass http://backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }

        include /etc/nginx/mime.types;
        default_type application/octet-stream;
    }

    events {
        worker_connections 1024;
    }
