apiVersion: v1
kind: ConfigMap
metadata:
  name: jtl-reporter-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    upstream backend {
        server {{ .Values.nginx.upstream.host }}:{{ .Values.nginx.upstream.port }};
    }

    server {
        listen 80;
        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
