apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jtl-reporter.fullname" . }}-config
data:
  DATABASE_URL: {{ .Values.env.migration.DATABASE_URL }}
  OPT_OUT_ANALYTICS: {{ .Values.env.migration.OPT_OUT_ANALYTICS | quote }}

