apiVersion: apps/v1
kind: Deployment
metadata:
  name: jtl-reporter-be
  namespace: {{ .Release.Namespace }}
  labels:
    app: jtl-reporter
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jtl-reporter
      tier: be
  template:
    metadata:
      labels:
        app: jtl-reporter
        tier: be
    spec:
      containers:
        - name: be
          image: {{ .Values.image.backend }}
          ports:
            - containerPort: {{ .Values.service.backend.port }}
          env:
            - name: DB_HOST
              value: {{ .Values.env.backend.DB_HOST }}
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jtl-reporter-secrets
                  key: JWT_TOKEN
            - name: JWT_TOKEN_LOGIN
              valueFrom:
                secretKeyRef:
                  name: jtl-reporter-secrets
                  key: JWT_TOKEN_LOGIN
          envFrom:
            - configMapRef:
                name: jtl-reporter-config
