{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jtl-reporter-ingress
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: jtl-reporter.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jtl-reporter-be
                port:
                  number: {{ .Values.service.backend.port }}
{{- end }}
