apiVersion: v1
kind: Secret
metadata:
  name: jtl-reporter-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  JWT_TOKEN: {{ .Values.env.backend.JWT_TOKEN | quote }}
  JWT_TOKEN_LOGIN: {{ .Values.env.backend.JWT_TOKEN_LOGIN | quote }}
