apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jtl-reporter.fullname" . }}-secrets
type: Opaque
data:
  JWT_TOKEN: {{ .Values.env.be.JWT_TOKEN | b64enc }}
  JWT_TOKEN_LOGIN: {{ .Values.env.be.JWT_TOKEN_LOGIN | b64enc }}