apiVersion: v1
kind: Service
metadata:
  name: jtl-reporter-be
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: 5000
  selector:
    app: jtl-reporter
    tier: be
---
apiVersion: v1
kind: Service
metadata:
  name: jtl-reporter-db
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.service.db.port }}
  selector:
    app: jtl-reporter
    tier: db
